# Generated by Django 6.1 on 2026-08-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('alt_titles', models.TextField(blank=True, default='')),
                ('isbn13', models.CharField(blank=True, default='', max_length=13)),
                ('publisher', models.CharField(blank=True, default='', max_length=512)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetectedSpine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('crop', models.ImageField(blank=True, upload_to='spine_crops/')),
                ('vlm_title', models.CharField(blank=True, default='', max_length=512)),
                ('vlm_author', models.CharField(blank=True, default='', max_length=512)),
                ('vlm_raw_response', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShelfPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shelf_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detection_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('vlm_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('matching_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('AUTO_ACCEPTED', 'Auto-accepted'), ('CONFIRMED', 'Confirmed'), ('CORRECTED', 'Corrected'), ('DISCARDED', 'Discarded')], default='PENDING_REVIEW', max_length=32)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='books.catalogbook')),
                ('spine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='books.detectedspine')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entries', to='books.catalogbook')),
                ('match_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entry', to='books.matchresult')),
            ],
            options={
                'verbose_name_plural': 'library entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='detectedspine',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spines', to='books.shelfphoto'),
        ),
    ]
