# Generated by Django 6.1 on 2026-08-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedspine',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedspine',
            name='crop',
            field=models.ImageField(blank=True, upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='shelfphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='shelf_photos/'),
        ),
    ]
