# Generated by Django 6.1 on 2026-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_detection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedspine',
            name='vlm_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'OK'), ('UNREADABLE', 'Unreadable')], default='PENDING', max_length=16),
        ),
    ]
